# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shopping_Stock_List' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shopping_Stock_List

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/AdMob'
pod 'Google-Mobile-Ads-SDK'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

  target 'Shopping_Stock_ListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Shopping_Stock_ListUITests' do
    # Pods for testing
  end

end
